var leveldata = [
	{type:"egg", posY: 200, posX: 600, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 100, posX: 900, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 170, posX: 1200, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 90, posX: 1500, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 40, posX: 1800, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 120, posX: 2100, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 180, posX: 2400, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 10, posX: 2700, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 200, posX: 3000, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 100, posX: 3300, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 170, posX: 3600, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 90, posX: 3900, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 40, posX: 4200, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 120, posX: 4500, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 180, posX: 4800, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 10, posX: 5100, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 200, posX: 5400, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 100, posX: 5700, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 170, posX: 6000, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 90, posX: 6300, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 40, posX: 6600, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 120, posX: 6900, spawned:false, despawned:false, removed:false},
	{type:"egg", posY: 180, posX: 7200, spawned:false, despawned:false, removed:false}
];